# Generated by Django 4.2 on 2023-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='taste_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_rating',
            field=models.IntegerField(),
        ),
    ]
