# Generated by Django 4.2 on 2023-04-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdmin',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.menu')),
            ],
            bases=('core.menu',),
        ),
        migrations.CreateModel(
            name='RestaurantAdmin',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.restaurant')),
            ],
            bases=('core.restaurant',),
        ),
        migrations.CreateModel(
            name='ReviewAdmin',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.review')),
            ],
            bases=('core.review',),
        ),
        migrations.AlterField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
