# Generated by Django 4.2 on 2023-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
